from challenge_msgs.msg._error import Error  # noqa: F401
